### ISSUE TITLE
WoW doesn't like the folder name.

### ISSUE THREAD

**Issue by GeekAndProud** [kstange/MasqueBlizzBars#1]
Renaming it MasqueBlizzBars will allow it to be loaded

**Comment by kstange** [comment]
The way that GitHub produces release files is the problem here, but it won't be a problem on the version that is packaged on CurseForge once that gets approved.  I can't do anything about the github Source zip file, as it always puts it into a subfolder called RepoName-Tag.  I've added the version that is actually uploaded to CurseForge though.
